// Generated by https://quicktype.io

export interface IResProducto {
    _id:    string;
    nombre: string;
    estado: boolean;
    precio: number;
    costo:  number;
    minimo: number;
    stock:  number;
    __v:    number;
}
